<a href="https://colab.research.google.com/github/samyak2475/ML-UDEMY/blob/main/2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

In [ ]:
import numpy as np

In [ ]:
np1 = np.array([1,2,3,4,5])

In [ ]:
np1

array([1, 2, 3, 4, 5])

In [ ]:
type(np1)

numpy.ndarray

In [ ]:
type(np1[2])

numpy.int64

In [ ]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np1.shape

(5,)

In [ ]:
mat1.shape

(3, 3)

In [ ]:
mat1.dtype

dtype('int64')

In [ ]:
type(mat1)

numpy.ndarray

In [ ]:
mat1 [0,0] = 5

In [ ]:
mat1

array([[5, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat1[0,0] = 1

In [ ]:
mat2 = np.arange(0,10,2) #arange - generates random values, only 'range' if using in a lsit

In [ ]:
mat2

array([0, 2, 4, 6, 8])

In [ ]:
mat3 = np.linspace(0,10,20) #linspace - generates linearly spaced valu20 being number of elemets

In [ ]:
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
mat3.shape

(20,)

In [ ]:
mat4 = np.random.rand(5,5) # generates ranndom matrix

In [ ]:
mat4

array([[0.36769343, 0.89423278, 0.4388753 , 0.84535876, 0.95307552],
       [0.64773862, 0.66299902, 0.72583831, 0.02516874, 0.759437  ],
       [0.51759961, 0.12947839, 0.57718001, 0.12084512, 0.93504683],
       [0.55683096, 0.83451223, 0.56182518, 0.25018809, 0.8427133 ],
       [0.93682311, 0.6501742 , 0.5636178 , 0.58245345, 0.89536636]])

In [ ]:
mat5 = np.random.randn(5,5) # generates random matrix with normal distribution

In [ ]:
mat5

array([[ 0.49418984,  0.37286584,  0.09365051, -1.89546485, -0.18507172],
       [ 1.46983105, -0.13103719, -0.09513528,  0.66411233, -0.32358949],
       [-0.63876875, -0.47730641,  0.50726932,  2.58114581,  0.49725642],
       [-0.48012246,  0.72280909, -0.4827191 ,  0.25895694,  1.74721546],
       [-1.22039986, -0.13283312, -0.53296558,  1.25119278,  0.1792    ]])



1.   np.diag
2.   np.zeros
3.   np.ones



In [ ]:
mat5[0,2]

np.float64(0.09365051361366572)

In [ ]:
mat5[0:3,:] # to get firt three rows

array([[ 0.49418984,  0.37286584,  0.09365051, -1.89546485, -0.18507172],
       [ 1.46983105, -0.13103719, -0.09513528,  0.66411233, -0.32358949],
       [-0.63876875, -0.47730641,  0.50726932,  2.58114581,  0.49725642]])

Q) mport the NumPy library and create a 1-dimensional NumPy array called 'a' with values [1, 2, 3, 4].

Then, store the shape of the array 'a' in a variable 'b'.


In [ ]:
import numpy as np
a = np.array([1,2,3,4])
b = a.shape

In [ ]:
b

(4,)

**PANDAS**

Specifically for data manipulation and analysis

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
df = pd.read_csv('/content/drive/MyDrive/Customer.csv')

In [5]:
df.head()

Customer ID    Customer Name    Segment  Age        Country  \
0    CG-12520      Claire Gute   Consumer   67  United States   
1    DV-13045  Darrin Van Huff  Corporate   31  United States   
2    SO-20335   Sean O'Donnell   Consumer   65  United States   
3    BH-11710  Brosina Hoffman   Consumer   20  United States   
4    AA-10480     Andrew Allen   Consumer   50  United States   

              City           State  Postal Code Region  
0        Henderson        Kentucky        42420  South  
1      Los Angeles      California        90036   West  
2  Fort Lauderdale         Florida        33311  South  
3      Los Angeles      California        90032   West  
4          Concord  North Carolina        28027  South

In [14]:
df1 = pd.read_csv('/content/drive/MyDrive/Customer.csv', header = 0, index_col = 0)

In [15]:
df1.head()

Customer Name    Segment  Age        Country             City  \
Customer ID                                                                    
CG-12520         Claire Gute   Consumer   67  United States        Henderson   
DV-13045     Darrin Van Huff  Corporate   31  United States      Los Angeles   
SO-20335      Sean O'Donnell   Consumer   65  United States  Fort Lauderdale   
BH-11710     Brosina Hoffman   Consumer   20  United States      Los Angeles   
AA-10480        Andrew Allen   Consumer   50  United States          Concord   

                      State  Postal Code Region  
Customer ID                                      
CG-12520           Kentucky        42420  South  
DV-13045         California        90036   West  
SO-20335            Florida        33311  South  
BH-11710         California        90032   West  
AA-10480     North Carolina        28027  South

In [17]:
df.describe() #statistics of data

Age   Postal Code
count  793.000000    793.000000
mean    44.467844  55229.717528
std     15.526673  31679.223816
min     18.000000   1841.000000
25%     31.000000  27217.000000
50%     45.000000  55901.000000
75%     58.000000  90004.000000
max     70.000000  99207.000000

In [18]:
df.iloc[0]

Customer ID           CG-12520
Customer Name      Claire Gute
Segment               Consumer
Age                         67
Country          United States
City                 Henderson
State                 Kentucky
Postal Code              42420
Region                   South
Name: 0, dtype: object