<a href="https://colab.research.google.com/github/samyak2475/ML-UDEMY/blob/main/2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3,4,5])

In [3]:
np1

array([1, 2, 3, 4, 5])

In [4]:
type(np1)

numpy.ndarray

In [5]:
type(np1[2])

numpy.int64

In [6]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np1.shape

(5,)

In [9]:
mat1.shape

(3, 3)

In [10]:
mat1.dtype

dtype('int64')

In [11]:
type(mat1)

numpy.ndarray

In [12]:
mat1 [0,0] = 5

In [13]:
mat1

array([[5, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
mat1[0,0] = 1

In [19]:
mat2 = np.arange(0,10,2) #arange - generates random values, only 'range' if using in a lsit

In [18]:
mat2

array([0, 2, 4, 6, 8])

In [24]:
mat3 = np.linspace(0,10,20) #linspace - generates linearly spaced valu20 being number of elemets

In [23]:
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [25]:
mat3.shape

(20,)

In [29]:
mat4 = np.random.rand(5,5) # generates ranndom matrix

In [30]:
mat4

array([[0.36769343, 0.89423278, 0.4388753 , 0.84535876, 0.95307552],
       [0.64773862, 0.66299902, 0.72583831, 0.02516874, 0.759437  ],
       [0.51759961, 0.12947839, 0.57718001, 0.12084512, 0.93504683],
       [0.55683096, 0.83451223, 0.56182518, 0.25018809, 0.8427133 ],
       [0.93682311, 0.6501742 , 0.5636178 , 0.58245345, 0.89536636]])

In [31]:
mat5 = np.random.randn(5,5) # generates random matrix with normal distribution

In [32]:
mat5

array([[ 0.49418984,  0.37286584,  0.09365051, -1.89546485, -0.18507172],
       [ 1.46983105, -0.13103719, -0.09513528,  0.66411233, -0.32358949],
       [-0.63876875, -0.47730641,  0.50726932,  2.58114581,  0.49725642],
       [-0.48012246,  0.72280909, -0.4827191 ,  0.25895694,  1.74721546],
       [-1.22039986, -0.13283312, -0.53296558,  1.25119278,  0.1792    ]])



1.   np.diag
2.   np.zeros
3.   np.ones



In [33]:
mat5[0,2]

np.float64(0.09365051361366572)

In [34]:
mat5[0:3,:] # to get firt three rows

array([[ 0.49418984,  0.37286584,  0.09365051, -1.89546485, -0.18507172],
       [ 1.46983105, -0.13103719, -0.09513528,  0.66411233, -0.32358949],
       [-0.63876875, -0.47730641,  0.50726932,  2.58114581,  0.49725642]])

Q) mport the NumPy library and create a 1-dimensional NumPy array called 'a' with values [1, 2, 3, 4].

Then, store the shape of the array 'a' in a variable 'b'.


In [35]:
import numpy as np
a = np.array([1,2,3,4])
b = a.shape

In [36]:
b

(4,)

**PANDAS**

Specifically for data manipulation and analysis

In [37]:
import pandas as pd